# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Aculisme"

[social.params]
icon = "brand-github"


[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/luca-mehl/"

[social.params]
icon = "brand-linkedin"


[[social]]
identifier = "email"
name = "Email"
url = "mailto:luca.mehl@gmail.com"

[social.params]
icon = "mail"

[[social]]
identifier = "cv"
name = "CV"
url = "/documents/luca_mehl_cv_22.04.2025.pdf"

[social.params]
icon = "file-cv"